import type { Metadata } from "next";
import ThemeProvider from "@/providers/theme-provider";
import QueryClientProvider from "@/providers/query-client-provider";

import "./globals.css";
import "@/styles/font.css"
import "@/styles/ant.css"
import '@/styles/json-viewer.css';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body dir="rtl">
        <ThemeProvider>
          <QueryClientProvider>
            {children}
          </QueryClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
